concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "PC"
  url = "https://gitlab.com/"
  id = 37223009
  token = "glrt-sk-eRiTPi61DnifhTCCE"
  token_obtained_at = 2024-05-27T09:53:31Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]

[[runners]]
  name = "PC"
  url = "https://gitlab.com/"
  id = 37223009
  token = "glrt-sk-eRiTPi61DnifhTCCE"
  token_obtained_at = 2024-05-27T09:56:15Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "shell"
  shell = "pwsh"
  [runners.custom_build_dir]
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
