apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  selector:
    app: springboot
  ports:
    - protocol: "TCP"
      port: 8080   # Port inside the cluster
      targetPort: 8080  # Port exposed by the container
      nodePort: 31965   # Port exposed to the outside
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  selector:
    matchLabels:
      app: springboot
  replicas: 3
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: chawkimersani/spring-boot-app:14
          ports:
            - containerPort: 8080
          env:   # Setting Environmental Variables
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/gw_logs?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: gw_logs
